## Problem Statement

### Student Name: Elana von der Heyden

In the last few years, wildfires have starting popping up in Europe in several countries, and has ravaged many homes and land. Although none have been very close to my home in Munich, Germany, my family has seen some taking place in Greece, and multiple other countries have been effected. The fires post an economic, health, and safety threat to families and individuals, and are likely an indicator of increasing global temperatures and underlying climate change.

[NASA Fire Information for Resource Management System (FIRMS)](https://firms.modaps.eosdis.nasa.gov/) uses a near real-time Moderate Resolution Imaging Spectroradiometer (MODIS) (among other tools, listed in the dataframe below) to capture fires as they happen worldwide, and publishes the data for public access with the use of an API key. Using longitudinal/latitudinal features and other features of the data published, it would be possible to use machine learning to attempt to predict where new wildfires might start. 

[Hundreds of firefighters battle a deadly forest fire raging in southern Greece for the third day (AP News)](https://apnews.com/article/greece-wildfire-peloponnese-forest-cfeb415e491edbdce660490bae5aeb3f)

[Europe's wildfires in 2023 were among the worst this century, report says (Reuters)](https://www.reuters.com/world/europe/europes-wildfires-2023-were-among-worst-this-century-report-says-2024-04-10/)


The data contains the following features:

- longitude (numeric)
- latitude (numeric)
- brightness (numeric) - this represents the intensity of the fire (e.g. higher = more intense fire)
- confidence (numeric) - this represents the confidence for a pixel from the images accurately detecting an active fire
- scan (numeric) - represents the approximate size of the imaged fire
- satellite (categorical) (either collected via Aqua or Terra satellite)
- acq_date and acq_time (date & time) - could be useful for understanding wildfire detection throughout the year and how trends might change seasonally

### Interesting questions may include:
- Where are wildfires most likely to occur? Is there one area that wildfires tend to cluster in occurence?
- Would it be possible to predict approximate wildfire locations based on certain features of the data, such as scan, longitude, latitude, and brightness?
- Is either the Terra or Aqua satellite more accurate in capturing wildfire location based on confidence rating?
- Are wildfires more common during certain times of the year? can we predict wildfire location and severity based on the time of year?

### Possible ML uses:
For exploring the questions above, there are a couple of different ML concepts that may be applicable. For understanding wildfire 'hotspots', K-means clustering could possibly be used to help identify patterns in the data points. Time series analysis could be used for understanding and predicting the seasonality of wildfires. Regression could also be used to understand if geographical location / territory affects fire intensity (brightness) and whether that could be used to predict fire intensity.

In [11]:
import pandas as pd

In [5]:
key = '996b2af0b72c07a0264d19e7d07e2bd5'

In [6]:
da_url = f'https://firms.modaps.eosdis.nasa.gov/api/data_availability/csv/{key}/all'
df = pd.read_csv(da_url)
display(df)

            data_id    min_date    max_date
0         MODIS_NRT  2024-07-01  2024-10-03
1          MODIS_SP  2000-11-01  2024-06-30
2  VIIRS_NOAA20_NRT  2019-12-04  2024-10-03
3  VIIRS_NOAA21_NRT  2024-01-17  2024-10-03
4    VIIRS_SNPP_NRT  2024-05-01  2024-10-03
5     VIIRS_SNPP_SP  2012-01-20  2024-04-30
6       LANDSAT_NRT  2022-06-20  2024-10-03
7          GOES_NRT  2022-08-09  2024-10-04
8          BA_MODIS  2000-11-01  2024-05-01

In [8]:
# The last four days of MODIS data for Greece
greece_url = f'https://firms.modaps.eosdis.nasa.gov/api/country/csv/{key}/MODIS_NRT/GRC/4'
df_greece = pd.read_csv(greece_url)
df_greece

,country_id,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight
0,GRC,38.04743,22.52417,321.61,2.73,1.58,2024-10-01,37,Aqua,MODIS,100,6.1NRT,284.59,91.74,N
1,GRC,38.04922,22.49664,326.88,2.74,1.58,2024-10-01,37,Aqua,MODIS,100,6.1NRT,283.49,117.26,N
2,GRC,38.05123,22.46533,313.14,2.75,1.59,2024-10-01,37,Aqua,MODIS,81,6.1NRT,283.08,60.33,N
3,GRC,38.05341,22.54635,303.61,2.71,1.58,2024-10-01,37,Aqua,MODIS,39,6.1NRT,285.34,30.99,N
4,GRC,38.05540,22.51838,340.73,2.73,1.58,2024-10-01,37,Aqua,MODIS,100,6.1NRT,286.76,198.58,N
5,GRC,38.05729,22.49177,342.21,2.74,1.58,2024-10-01,37,Aqua,MODIS,100,6.1NRT,285.98,208.95,N
6,GRC,38.05945,22.46130,328.75,2.75,1.59,2024-10-01,37,Aqua,MODIS,100,6.1NRT,284.93,124.45,N
7,GRC,38.06140,22.43353,320.85,2.76,1.59,2024-10-01,37,Aqua,MODIS,100,6.1NRT,284.42,89.31,N
8,GRC,38.06163,22.52282,333.28,2.73,1.58,2024-10-01,37,Aqua,MODIS,100,6.1NRT,287.20,150.56,N
9,GRC,38.06333,22.49690,317.86,2.74,1.58,2024-10-01,37,Aqua,MODIS,96,6.1NRT,284.76,74.75,N
10,GRC,38.06531,22.46664,325.19,2.75,1.59,2024-10-01,37,Aqua,MODIS,100,6.1NRT,285.13,106.09,N
11,GRC,38.06718,22.43799,331.40,2.76,1.59,2024-10-01,37,Aqua,MODIS,100,6.1NRT,286.46,142.29,N
12,GRC,38.07358,22.46186,309.10,2.75,1.59,2024-10-01,37,Aqua,MODIS,44,6.1NRT,284.05,42.48,N
13,GRC,38.07587,22.42992,326.37,2.76,1.59,2024-10-01,37,Aqua,MODIS,100,6.1NRT,286.14,114.59,N
14,GRC,38.08162,22.43414,324.42,2.76,1.59,2024-10-01,37,Aqua,MODIS,100,6.1NRT,285.87,105.74,N
15,GRC,38.09790,22.40287,300.05,2.78,1.59,2024-10-01,37,Aqua,MODIS,8,6.1NRT,285.42,23.03,N
16,GRC,38.03563,22.47758,332.04,2.17,1.43,2024-10-01,803,Terra,MODIS,86,6.1NRT,291.78,88.36,D
17,GRC,38.03687,22.45000,313.65,2.18,1.43,2024-10-01,803,Terra,MODIS,18,6.1NRT,291.22,29.47,D
18,GRC,38.03728,22.45511,328.63,2.18,1.43,2024-10-01,803,Terra,MODIS,84,6.1NRT,291.52,75.39,D
19,GRC,38.04221,22.54269,309.23,2.15,1.42,2024-10-01,803,Terra,MODIS,37,6.1NRT,293.05,19.26,D
20,GRC,38.04486,22.52523,331.73,2.15,1.43,2024-10-01,803,Terra,MODIS,86,6.1NRT,294.97,86.28,D
21,GRC,38.04784,22.47306,333.09,2.17,1.43,2024-10-01,803,Terra,MODIS,84,6.1NRT,296.39,88.93,D
22,GRC,38.04829,22.47941,327.94,2.17,1.43,2024-10-01,803,Terra,MODIS,56,6.1NRT,296.29,64.65,D
23,GRC,38.04974,22.44950,317.91,2.18,1.43,2024-10-01,803,Terra,MODIS,35,6.1NRT,293.25,37.11,D
24,GRC,38.05014,22.45461,326.56,2.18,1.43,2024-10-01,803,Terra,MODIS,50,6.1NRT,294.14,59.75,D
25,GRC,38.08102,22.38531,324.34,2.20,1.44,2024-10-01,803,Terra,MODIS,68,6.1NRT,296.66,54.85,D
26,GRC,38.03690,22.52711,322.20,3.16,1.68,2024-10-01,1140,Aqua,MODIS,76,6.1NRT,293.97,87.29,D
27,GRC,38.04915,22.52418,302.32,2.73,1.58,2024-10-01,1906,Terra,MODIS,48,6.1NRT,285.77,30.19,N
28,GRC,40.70238,22.80626,309.66,1.00,1.00,2024-10-02,117,Aqua,MODIS,78,6.1NRT,281.60,12.98,N
29,GRC,39.50203,22.51331,318.05,1.06,1.03,2024-10-02,843,Terra,MODIS,68,6.1NRT,303.17,8.03,D
30,GRC,39.50393,22.50141,316.40,1.06,1.03,2024-10-02,843,Terra,MODIS,57,6.1NRT,303.29,6.60,D
31,GRC,40.47731,23.32227,312.78,1.09,1.04,2024-10-02,843,Terra,MODIS,65,6.1NRT,296.81,9.43,D
32,GRC,40.47937,23.30974,312.27,1.09,1.04,2024-10-02,843,Terra,MODIS,64,6.1NRT,295.91,9.39,D
33,GRC,40.63862,23.07046,305.34,1.07,1.03,2024-10-02,843,Terra,MODIS,47,6.1NRT,295.29,4.84,D
34,GRC,41.04014,24.82835,310.02,1.22,1.10,2024-10-02,843,Terra,MODIS,55,6.1NRT,297.67,6.20,D
35,GRC,41.04966,24.83132,308.08,1.22,1.10,2024-10-02,843,Terra,MODIS,41,6.1NRT,296.18,4.43,D

In [16]:
# The last 3 days of all of mainland Europe (based on bounding region coordinates 36,-10,40,71)
area_url = f'https://firms.modaps.eosdis.nasa.gov/api/area/csv/{key}/VIIRS_NOAA20_NRT/36,-10,40,71/3'
df_area = pd.read_csv(area_url)

df_area

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,59.12985,37.81826,300.73,0.43,0.38,2024-10-02,9,N20,VIIRS,n,2.0NRT,280.11,0.83,N
1,59.13083,37.79456,318.79,0.43,0.38,2024-10-02,9,N20,VIIRS,n,2.0NRT,285.97,14.77,N
2,59.13225,37.78749,304.35,0.43,0.38,2024-10-02,9,N20,VIIRS,n,2.0NRT,278.69,7.49,N
3,59.14016,37.84229,297.80,0.43,0.38,2024-10-02,9,N20,VIIRS,n,2.0NRT,280.46,1.48,N
4,59.14202,37.85189,298.81,0.43,0.38,2024-10-02,9,N20,VIIRS,n,2.0NRT,278.11,1.31,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4707,23.94954,38.26140,310.25,0.33,0.55,2024-10-03,2341,N20,VIIRS,n,2.0NRT,297.26,1.58,N
4708,23.95100,38.27858,312.89,0.33,0.55,2024-10-03,2341,N20,VIIRS,n,2.0NRT,297.33,1.23,N
4709,28.47111,36.51955,305.45,0.42,0.45,2024-10-03,2341,N20,VIIRS,n,2.0NRT,292.26,1.10,N
4710,21.34191,39.24493,321.52,0.43,0.62,2024-10-03,2344,N20,VIIRS,n,2.0NRT,293.51,1.66,N
4711,54.21451,38.92333,295.19,0.70,0.75,2024-10-04,113,N20,VIIRS,n,2.0NRT,275.35,2.40,N